import { jsPDF } from 'jspdf';
import { PDFDocument, StandardFonts, rgb } from 'pdf-lib';
import UTIF from 'utif';
import type { ChecklistReport, StoredFile } from '../types';
import { checklistFileNameBase, dataUrlToUint8 } from './helpers';
import logoUrl from '../assets/sabesp-logo.jpg';

const BLUE=[7,143,190] as const, CYAN=[17,166,204] as const, TEXT_BLUE=[7,133,177] as const;
const DARK=[47,59,68] as const, LIGHT=[240,244,246] as const, BORDER=[200,208,214] as const, NAVY=[18,65,91] as const;
const PAGE_W=210,PAGE_H=297,M=10,HEADER_BOTTOM=35,CONTENT_BOTTOM=264,LINE_H=3.4,PAD_Y=1.6;
let cachedLogo:string|null=null;

async function getLogoDataUrl(){if(cachedLogo)return cachedLogo;const blob=await fetch(logoUrl).then(r=>r.blob());cachedLogo=await new Promise<string>(res=>{const rd=new FileReader();rd.onload=()=>res(String(rd.result));rd.readAsDataURL(blob)});return cachedLogo;}
function now(){return new Date().toLocaleString('pt-BR')}
function wrap(doc:jsPDF,text:unknown,width:number){return doc.splitTextToSize(String(text??''),width) as string[]}
function addHeader(doc:jsPDF,r:ChecklistReport,logo:string){doc.setFont('helvetica','normal');doc.setFontSize(6.6);doc.setTextColor(65,75,82);doc.text(now(),M,7.2);doc.setFont('helvetica','bold');doc.setFontSize(6.3);doc.setTextColor(...BLUE);doc.text('Desenvolvido pelo Polo de Manutenção Suzano - OLMS',PAGE_W-M,7.2,{align:'right'});doc.text('Eng° Eder Nunes',PAGE_W-M,10.4,{align:'right'});doc.addImage(logo,'JPEG',11,10,18,18,undefined,'FAST');doc.setTextColor(...BLUE);doc.setFont('helvetica','bold');doc.setFontSize(11.2);doc.text('CHECKLIST DE LIBERAÇÃO DE OBRA',PAGE_W/2,17.2,{align:'center'});doc.setTextColor(...DARK);doc.setFontSize(7.8);const sub=[r.obra.municipio,r.obra.endereco,r.obra.tipoObra,r.obra.aguaEsgoto].filter(Boolean).join('  |  ');doc.text((wrap(doc,sub,166)).slice(0,2),PAGE_W/2,24.4,{align:'center'});doc.setDrawColor(...CYAN);doc.setLineWidth(.8);doc.line(M,32,PAGE_W-M,32)}
function section(doc:jsPDF,title:string,y:number){doc.setFillColor(...BLUE);doc.roundedRect(M,y,PAGE_W-M*2,7.2,1.6,1.6,'F');doc.setTextColor(255,255,255);doc.setFont('helvetica','bold');doc.setFontSize(8.7);doc.text(title,M+2.3,y+4.9);doc.setTextColor(...DARK);return y+9}
function ensure(doc:jsPDF,r:ChecklistReport,logo:string,y:number,needed=15){if(y+needed<=CONTENT_BOTTOM)return y;doc.addPage();addHeader(doc,r,logo);return HEADER_BOTTOM}
function infoTable(doc:jsPDF,rows:Array<[string,string]>,y:number){doc.setLineWidth(.1);const widths=[8,68,PAGE_W-2*M-76],x=M;rows.forEach(([label,value],i)=>{doc.setFontSize(7.5);doc.setFont('helvetica','bold');const labelLines=wrap(doc,label,widths[1]-4);doc.setFont('helvetica','normal');const valueLines=wrap(doc,value||'-',widths[2]-4);const h=Math.max(5,Math.max(labelLines.length,valueLines.length)*LINE_H+PAD_Y*2);doc.setDrawColor(...BORDER);doc.setFillColor(255,255,255);doc.rect(x,y,widths[0],h,'FD');doc.setFont('helvetica','normal');doc.setTextColor(...DARK);doc.text(String(i+1),x+widths[0]/2,y+PAD_Y+2.4,{align:'center'});doc.setFillColor(...LIGHT);doc.rect(x+widths[0],y,widths[1],h,'FD');doc.setFont('helvetica','bold');doc.setTextColor(...TEXT_BLUE);doc.text(labelLines,x+widths[0]+2,y+PAD_Y+2.4,{maxWidth:widths[1]-4});doc.setFillColor(255,255,255);doc.rect(x+widths[0]+widths[1],y,widths[2],h,'FD');doc.setFont('helvetica','normal');doc.setTextColor(...DARK);doc.text(String(value||'-'),x+widths[0]+widths[1]+2,y+PAD_Y+2.4,{maxWidth:widths[2]-4,align:valueLines.length>1?'justify':'left'});y+=h});return y+3}
function paragraph(doc:jsPDF,text:string,y:number){const width=PAGE_W-2*M-4;doc.setFont('helvetica','normal');doc.setFontSize(7.6);const lines=wrap(doc,text,width);const h=Math.max(7,lines.length*LINE_H+PAD_Y*2);doc.setLineWidth(.1);doc.setDrawColor(...BORDER);doc.setFillColor(255,255,255);doc.rect(M,y,PAGE_W-2*M,h,'FD');doc.setTextColor(...DARK);doc.text(text||'-',M+2,y+PAD_Y+2.5,{maxWidth:width,align:lines.length>1?'justify':'left'});return y+h+3}
function statusColor(status:string){if(status==='SIM')return [22,110,47] as const;if(status==='NÃO')return [180,25,25] as const;return [110,118,126] as const}
function drawChecklist(doc:jsPDF,r:ChecklistReport,logo:string,startY:number){const widths=[72,30,88],heads=['Documento','Situação','Observações do campo'];let y=startY;const header=()=>{let x=M;doc.setFont('helvetica','bold');doc.setFontSize(6.7);heads.forEach((h,i)=>{doc.setFillColor(...NAVY);doc.setDrawColor(...BORDER);doc.rect(x,y,widths[i],7.5,'FD');doc.setTextColor(255,255,255);doc.text(h,x+widths[i]/2,y+4.8,{align:'center',maxWidth:widths[i]-2});x+=widths[i]});y+=7.5};header();for(const item of r.checklist){const vals=[item.documento,item.situacao||'-',item.orientacao];const lines=vals.map((v,i)=>wrap(doc,v,widths[i]-2.8));const h=Math.max(5,Math.max(...lines.map(l=>l.length))*LINE_H+PAD_Y*2);const old=y;y=ensure(doc,r,logo,y,h+2);if(y!==old&&y===HEADER_BOTTOM){y=section(doc,'Checklist dos documentos - continuação',y);header()}let x=M;for(let i=0;i<3;i++){doc.setFillColor(255,255,255);doc.setDrawColor(...BORDER);doc.rect(x,y,widths[i],h,'FD');doc.setFont('helvetica',i===1?'bold':'normal');doc.setFontSize(6.8);const c=i===1?statusColor(item.situacao):DARK;doc.setTextColor(c[0],c[1],c[2]);doc.text(lines[i],i===1?x+widths[i]/2:x+1.4,y+PAD_Y+2.3,{align:i===1?'center':'left',maxWidth:widths[i]-2.8});x+=widths[i]}y+=h}doc.setTextColor(...DARK);return y+3}


function drawAttachmentIndex(doc:jsPDF,r:ChecklistReport,logo:string,y:number){
  if(!r.anexos.length)return y;
  y=ensure(doc,r,logo,y,14);y=section(doc,'Anexos',y);
  for(let i=0;i<r.anexos.length;i++){
    const a=r.anexos[i];
    const title=`Anexo ${i+1}: ${a.titulo||a.name}`;
    doc.setFont('helvetica','bold');doc.setFontSize(7.4);const titleLines=wrap(doc,title,PAGE_W-2*M-4);
    doc.setFont('helvetica','normal');const descLines=wrap(doc,a.descricao||'-',PAGE_W-2*M-20);
    const h=Math.max(9,(titleLines.length+descLines.length)*LINE_H+PAD_Y*2+1);
    y=ensure(doc,r,logo,y,h+2);
    doc.setDrawColor(...BORDER);doc.setFillColor(255,255,255);doc.rect(M,y,PAGE_W-2*M,h,'FD');
    doc.setFont('helvetica','bold');doc.setTextColor(...TEXT_BLUE);doc.text(titleLines,M+2,y+PAD_Y+2.4,{maxWidth:PAGE_W-2*M-4});
    const descY=y+PAD_Y+2.4+titleLines.length*LINE_H;
    doc.setFont('helvetica','bold');doc.setTextColor(...DARK);doc.text('Descrição:',M+2,descY);
    const lw=doc.getTextWidth('Descrição: ')+1;doc.setFont('helvetica','normal');doc.text(a.descricao||'-',M+2+lw,descY,{maxWidth:PAGE_W-2*M-4-lw,align:descLines.length>1?'justify':'left'});
    y+=h+2;
  }
  return y;
}

async function buildBase(r:ChecklistReport){const logo=await getLogoDataUrl(),doc=new jsPDF({unit:'mm',format:'a4',orientation:'portrait',compress:true});addHeader(doc,r,logo);let y=section(doc,'Identificação do responsável pela elaboração do relatório',HEADER_BOTTOM);y=infoTable(doc,[['Elaborado por',r.responsavel.elaboradoPor],['Data',r.responsavel.data?new Date(`${r.responsavel.data}T12:00:00`).toLocaleDateString('pt-BR'):''],['Matrícula',r.responsavel.matricula],['Cargo/Função',r.responsavel.cargo],['Unidade',r.responsavel.unidade]],y);y=ensure(doc,r,logo,y,48);y=section(doc,'Dados da Obra',y);const obra:Array<[string,string]>=[['Município',r.obra.municipio],['Endereço',r.obra.endereco],['Tipo de Serviço',r.obra.tipoObra],['Água/Esgoto',r.obra.aguaEsgoto],['Empresa Executora',r.obra.empresaExecutora],['Contrato',r.obra.contrato]];if(r.obra.descricaoComplementar)obra.push(['Descrição complementar',r.obra.descricaoComplementar]);y=infoTable(doc,obra,y);y=ensure(doc,r,logo,y,20);y=section(doc,'Checklist dos documentos',y);y=drawChecklist(doc,r,logo,y);if(r.observacoesGerais){y=ensure(doc,r,logo,y,20);y=section(doc,'Observações gerais',y);y=paragraph(doc,r.observacoesGerais,y)}y=drawAttachmentIndex(doc,r,logo,y);return doc.output('arraybuffer')}

async function tiffToJpegs(file:StoredFile){const bytes=dataUrlToUint8(file.data),buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),ifds=UTIF.decode(buffer),images:Array<{data:string;width:number;height:number}>=[];for(const ifd of ifds){UTIF.decodeImage(buffer,ifd);const rgba=UTIF.toRGBA8(ifd),canvas=document.createElement('canvas');canvas.width=ifd.width;canvas.height=ifd.height;const ctx=canvas.getContext('2d');if(!ctx)continue;ctx.putImageData(new ImageData(new Uint8ClampedArray(rgba),ifd.width,ifd.height),0,0);images.push({data:canvas.toDataURL('image/jpeg',.94),width:ifd.width,height:ifd.height})}return images}
function imageSize(dataUrl:string){return new Promise<{width:number;height:number}>((resolve,reject)=>{const img=new Image();img.onload=()=>resolve({width:img.naturalWidth,height:img.naturalHeight});img.onerror=reject;img.src=dataUrl})}
async function appendOriginalAttachments(out:PDFDocument,r:ChecklistReport){for(let i=0;i<r.anexos.length;i++){const a=r.anexos[i];if(!a.data)continue;const isPdf=/pdf/i.test(a.type)||/\.pdf$/i.test(a.name);if(isPdf){try{const bytes=dataUrlToUint8(a.data),src=await PDFDocument.load(bytes),copied=await out.copyPages(src,src.getPageIndices());copied.forEach(p=>out.addPage(p))}catch(e){console.warn('Falha ao incorporar PDF',a.name,e)}continue}const raster=/tiff?/i.test(a.type)||/\.tiff?$/i.test(a.name)?await tiffToJpegs(a):[{data:a.data,...await imageSize(a.data)}];for(const img of raster){try{const bytes=dataUrlToUint8(img.data),embedded=img.data.startsWith('data:image/png')?await out.embedPng(bytes):await out.embedJpg(bytes);const pxToPt=.75;const width=Math.max(1,img.width*pxToPt),height=Math.max(1,img.height*pxToPt);const page=out.addPage([width,height]);page.drawImage(embedded,{x:0,y:0,width,height})}catch(e){console.warn('Falha ao incorporar imagem',a.name,e)}}}}
async function stampBody(pdf:PDFDocument,bodyPages:number){const font=await pdf.embedFont(StandardFonts.Helvetica),blue=rgb(CYAN[0]/255,CYAN[1]/255,CYAN[2]/255),pages=pdf.getPages();for(let i=0;i<bodyPages;i++){const page=pages[i],{width}=page.getSize();page.drawLine({start:{x:28,y:39},end:{x:width-28,y:39},thickness:.9,color:blue});['Companhia de Saneamento Básico do Estado de São Paulo - Sabesp','Divisão de Manutenção e Serviços Operacionais Suzano - OLMS','Rua Benjamin Constant 1980 - Centro | CEP 08674-179 | Suzano - SP','www.sabesp.com.br'].forEach((line,idx)=>page.drawText(line,{x:28,y:30-idx*6.1,size:5.2,font,color:blue}));page.drawText(`${i+1}`,{x:width-42,y:13,size:6.2,font,color:blue})}}
export type GeneratedChecklistPdf={blob:Blob;url:string;fileName:string};
export async function generateChecklistPdf(r:ChecklistReport):Promise<GeneratedChecklistPdf>{const base=await buildBase(r),out=await PDFDocument.load(base),bodyPages=out.getPageCount();await stampBody(out,bodyPages);await appendOriginalAttachments(out,r);const bytes=await out.save({useObjectStreams:true});const blob=new Blob([bytes as unknown as BlobPart],{type:'application/pdf'});return{blob,url:URL.createObjectURL(blob),fileName:`${checklistFileNameBase(r,new Date())}.pdf`}}
