import { jsPDF } from 'jspdf';
import { PDFDocument, StandardFonts, rgb, type PDFFont } from 'pdf-lib';
import UTIF from 'utif';
import type { PhotoReport, StoredFile } from '../types';
import { dataUrlToUint8, photoFileNameBase } from './helpers';
import logoUrl from '../assets/sabesp-logo.jpg';

const PHOTO_OBJECTIVES: Record<string, string> = {
  'PRÉ-OBRA': 'Registrar as condições existentes da área de intervenção e de suas adjacências antes do início dos serviços, por meio de levantamento fotográfico, visando documentar o estado de conservação de pavimentos, calçadas, guias, sarjetas, dispositivos urbanos, imóveis lindeiros e demais elementos que possam ser influenciados pela execução da obra.',
  'ACOMPANHAMENTO DE OBRA': 'Registrar a evolução física dos serviços durante a execução da obra, por meio de acompanhamento fotográfico das etapas construtivas, das frentes de trabalho, das condições operacionais e das soluções adotadas, possibilitando o controle, monitoramento e rastreabilidade das atividades executadas.',
  'FINAL DE OBRA': 'Registrar a situação da área após a conclusão dos serviços, evidenciando a execução do objeto contratado, a recomposição das áreas afetadas, a restauração das condições operacionais do local e o atendimento às condições previstas para encerramento da intervenção.',
  'OCORRÊNCIAS': 'Registrar e documentar fatos, eventos, não conformidades, interferências, emergências, danos, solicitações de terceiros ou quaisquer situações relevantes identificadas durante as atividades, fornecendo evidências para análise técnica, tomada de decisão, controle contratual e eventual instrução de processos administrativos ou judiciais.',
  'SINISTRO': 'Registrar e documentar, por meio de levantamento fotográfico, os fatos, condições, danos, avarias, impactos e demais evidências relacionados à ocorrência de sinistro, visando caracterizar a situação reclamada, identificar os elementos afetados, subsidiar análises técnicas, apuração de responsabilidades, avaliação de prejuízos, definição de ações corretivas e mitigadoras, bem como fornecer suporte documental para processos administrativos, contratuais, securitários, judiciais ou extrajudiciais.',
};
const BLUE=[7,143,190] as const,CYAN=[17,166,204] as const,DARK=[47,59,68] as const,BORDER=[200,208,214] as const,LIGHT=[240,244,246] as const;
const M=10,W=210,BOT=264,TOP=35,LINE_H=3.4,PAD_Y=1.6;let cache:string|null=null;
async function logo(){if(cache)return cache;const b=await fetch(logoUrl).then(r=>r.blob());cache=await new Promise<string>(res=>{const rd=new FileReader();rd.onload=()=>res(String(rd.result));rd.readAsDataURL(b)});return cache}
function wrap(d:jsPDF,t:unknown,w:number){return d.splitTextToSize(String(t??''),w) as string[]}
function header(d:jsPDF,r:PhotoReport,l:string){d.addImage(l,'JPEG',11,10,18,18);d.setFont('helvetica','bold');d.setFontSize(10.8);d.setTextColor(BLUE[0],BLUE[1],BLUE[2]);d.text('RELATÓRIO FOTOGRÁFICO',W/2,17,{align:'center'});d.setFontSize(6.3);d.text('Desenvolvido pelo Polo de Manutenção Suzano - OLMS',W-M,7.2,{align:'right'});d.text('Eng° Eder Nunes',W-M,10.4,{align:'right'});d.setTextColor(DARK[0],DARK[1],DARK[2]);d.setFontSize(7.5);d.text([r.caracterizacao.tipoRelatorio,r.obra.municipio,r.obra.endereco].filter(Boolean).join(' | '),W/2,24,{align:'center',maxWidth:165});d.setDrawColor(CYAN[0],CYAN[1],CYAN[2]);d.setLineWidth(.8);d.line(M,32,W-M,32)}
function sec(d:jsPDF,t:string,y:number){d.setFillColor(BLUE[0],BLUE[1],BLUE[2]);d.roundedRect(M,y,W-2*M,7,1.5,1.5,'F');d.setTextColor(255,255,255);d.setFont('helvetica','bold');d.setFontSize(8.5);d.text(t,M+2,y+4.8);d.setTextColor(DARK[0],DARK[1],DARK[2]);return y+9}
function ensure(d:jsPDF,r:PhotoReport,l:string,y:number,n=15){if(y+n<=BOT)return y;d.addPage();header(d,r,l);return TOP}
function table(d:jsPDF,r:PhotoReport,l:string,rows:[string,string][],y:number){for(const[a,b]of rows){d.setFontSize(6.5);d.setFont('helvetica','bold');const ll=wrap(d,a,58);d.setFont('helvetica','normal');const vl=wrap(d,b||'-',W-2*M-66);const lines=Math.max(ll.length,vl.length);const h=Math.max(5,lines*LINE_H+PAD_Y*2);y=ensure(d,r,l,y,h);d.setDrawColor(BORDER[0],BORDER[1],BORDER[2]);d.setLineWidth(.1);d.setFillColor(LIGHT[0],LIGHT[1],LIGHT[2]);d.rect(M,y,62,h,'FD');d.setFillColor(255,255,255);d.rect(M+62,y,W-2*M-62,h,'FD');d.setFont('helvetica','bold');d.text(ll,M+2,y+PAD_Y+2.2,{maxWidth:58});d.setFont('helvetica','normal');d.text(vl,M+64,y+PAD_Y+2.2,{maxWidth:W-2*M-66});y+=h}return y+2}
function para(d:jsPDF,r:PhotoReport,l:string,t:string,y:number){const width=W-2*M-4;d.setFont('helvetica','normal');d.setFontSize(7.2);const lines=wrap(d,t,width),h=Math.max(7,lines.length*LINE_H+PAD_Y*2);y=ensure(d,r,l,y,h);d.setDrawColor(BORDER[0],BORDER[1],BORDER[2]);d.rect(M,y,W-2*M,h);d.text(String(t||'-'),M+2,y+PAD_Y+2.4,{maxWidth:width,align:lines.length>1?'justify':'left'});return y+h+3}
function size(url:string):Promise<{width:number;height:number}>{return new Promise((res,rej)=>{const i=new Image();i.onload=()=>res({width:i.naturalWidth,height:i.naturalHeight});i.onerror=rej;i.src=url})}
async function fit(d:jsPDF,url:string,x:number,y:number,w:number,h:number){const s=await size(url),k=Math.min(w/s.width,h/s.height),dw=s.width*k,dh=s.height*k;d.addImage(url,url.startsWith('data:image/png')?'PNG':'JPEG',x+(w-dw)/2,y+(h-dh)/2,dw,dh,undefined,'FAST')}
async function tiff(f:StoredFile){const bytes=dataUrlToUint8(f.data),buf=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),ifds=UTIF.decode(buf),out:string[]=[];for(const ifd of ifds){UTIF.decodeImage(buf,ifd);const rgba=UTIF.toRGBA8(ifd),c=document.createElement('canvas');c.width=ifd.width;c.height=ifd.height;const ctx=c.getContext('2d');if(!ctx)continue;ctx.putImageData(new ImageData(new Uint8ClampedArray(rgba),ifd.width,ifd.height),0,0);out.push(c.toDataURL('image/jpeg',.92))}return out}
function dateLine(municipio:string,date:string){const dt=date?new Date(`${date}T12:00:00`):new Date();const day=dt.getDate(),month=dt.toLocaleDateString('pt-BR',{month:'long'}),year=dt.getFullYear();return `${municipio||''}, ${day} de ${month} de ${year}`}
function signature(d:jsPDF,r:PhotoReport,l:string,y:number){y=ensure(d,r,l,y,36);const dateY=y+7;d.setFont('helvetica','normal');d.setFontSize(7.5);d.setTextColor(DARK[0],DARK[1],DARK[2]);d.text(dateLine(r.obra.municipio,r.responsavel.data),W-M,dateY,{align:'right'});const sigY=dateY+24;d.setFont('helvetica','bold');d.setFontSize(9);d.text(r.responsavel.elaboradoPor||'-',M,sigY);d.setFont('helvetica','normal');d.setFontSize(7.5);d.text(r.responsavel.cargo||'-',M,sigY+4.5);return sigY+8}
function attachmentHeader(d:jsPDF,a:StoredFile,index:number,page:number,total:number,y:number){const title=a.titulo||a.name;let ny=sec(d,`Anexo ${index+1}: ${title} – ${page} de ${total}`,y);if(a.descricao){d.setFontSize(7.1);d.setTextColor(DARK[0],DARK[1],DARK[2]);d.setFont('helvetica','bold');d.text('Descrição:',M,ny+3.8);const lw=d.getTextWidth('Descrição: ')+1;d.setFont('helvetica','normal');const lines=wrap(d,a.descricao,W-2*M-lw);d.text(a.descricao,M+lw,ny+3.8,{maxWidth:W-2*M-lw,align:lines.length>1?'justify':'left'});ny+=Math.max(7,lines.length*LINE_H+2)}return ny}
async function base(r:PhotoReport){const l=await logo(),d=new jsPDF({unit:'mm',format:'a4',compress:true});header(d,r,l);let y=sec(d,'1. Caracterização do relatório',TOP);y=table(d,r,l,[['Tipo de relatório',r.caracterizacao.tipoRelatorio],['Informação complementar',r.caracterizacao.informacaoComplementar]],y);y=sec(d,'2. Objetivo',ensure(d,r,l,y,25));y=para(d,r,l,PHOTO_OBJECTIVES[r.caracterizacao.tipoRelatorio]||'',y);y=sec(d,'3. Identificação do responsável pela elaboração do relatório',ensure(d,r,l,y,30));y=table(d,r,l,[['Elaborado por',r.responsavel.elaboradoPor],['Data',r.responsavel.data?new Date(r.responsavel.data+'T12:00:00').toLocaleDateString('pt-BR'):''],['Matrícula',r.responsavel.matricula],['Cargo/Função',r.responsavel.cargo],['Empresa',r.responsavel.empresa]],y);y=sec(d,'4. Dados da Obra',ensure(d,r,l,y,35));y=table(d,r,l,[['Município',r.obra.municipio],['Endereço',r.obra.endereco],['Tipo de Serviço',r.obra.tipoObra],['Água/Esgoto',r.obra.aguaEsgoto],['Empresa Executora',r.obra.empresaExecutora],['Contrato',r.obra.contrato],['Descrição complementar',r.obra.descricaoComplementar]],y);if(r.observacoesGerais){y=sec(d,'5. Observações gerais da vistoria',ensure(d,r,l,y,20));y=para(d,r,l,r.observacoesGerais,y)}
  for(let i=0;i<r.fotos.length;i++){const f=r.fotos[i];d.addPage();header(d,r,l);let py=sec(d,`Foto ${i+1}: ${f.titulo}`,TOP);if(f.descricao){d.setFontSize(7.2);d.setTextColor(DARK[0],DARK[1],DARK[2]);d.setFont('helvetica','bold');d.text('Descrição:',M,py+3.8);const lw=d.getTextWidth('Descrição: ')+1;d.setFont('helvetica','normal');const lines=wrap(d,f.descricao,W-2*M-lw);d.text(f.descricao,M+lw,py+3.8,{maxWidth:W-2*M-lw,align:lines.length>1?'justify':'left'});py+=Math.max(7,lines.length*LINE_H+2)}const reserve=0;if(f.imagem)await fit(d,f.imagem.data,M+2,py+2,W-2*M-4,Math.max(20,BOT-py-4-reserve))}

  for(let ai=0;ai<r.anexos.length;ai++){const a=r.anexos[ai];if(/pdf/i.test(a.type)||/\.pdf$/i.test(a.name))continue;const pages=/tiff?/i.test(a.type)||/\.tiff?$/i.test(a.name)?await tiff(a):[a.data];for(let pi=0;pi<pages.length;pi++){d.addPage();header(d,r,l);const ay=attachmentHeader(d,a,ai,pi+1,pages.length,TOP);await fit(d,pages[pi],M+2,ay+2,W-2*M-4,BOT-ay-4)}}return d.output('arraybuffer')}
function wrapPdfLib(text:string,font:PDFFont,size:number,maxWidth:number){const words=text.split(/\s+/),lines:string[]=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(font.widthOfTextAtSize(test,size)<=maxWidth)line=test;else{if(line)lines.push(line);line=word}}if(line)lines.push(line);return lines}
async function merge(base:ArrayBuffer,r:PhotoReport){const out=await PDFDocument.load(base),bold=await out.embedFont(StandardFonts.HelveticaBold),font=await out.embedFont(StandardFonts.Helvetica);for(let ai=0;ai<r.anexos.length;ai++){const a=r.anexos[ai];if(!(/pdf/i.test(a.type)||/\.pdf$/i.test(a.name)))continue;try{const bytes=dataUrlToUint8(a.data),ext=await PDFDocument.load(bytes),pages=await out.embedPdf(bytes,ext.getPageIndices());for(let pi=0;pi<pages.length;pi++){const p=out.addPage([595.28,841.89]),e=pages[pi],scale=Math.min(535/e.width,680/e.height),dw=e.width*scale,dh=e.height*scale;p.drawRectangle({x:28,y:775,width:539,height:20,color:rgb(BLUE[0]/255,BLUE[1]/255,BLUE[2]/255)});p.drawText(`Anexo ${ai+1}: ${a.titulo||a.name} – ${pi+1} de ${pages.length}`,{x:35,y:781,size:8,font:bold,color:rgb(1,1,1)});let descBottom=755;if(a.descricao){p.drawText('Descrição:',{x:28,y:760,size:6.5,font:bold});const labelW=bold.widthOfTextAtSize('Descrição: ',6.5);const lines=wrapPdfLib(a.descricao,font,6.5,539-labelW);lines.forEach((line,j)=>p.drawText(line,{x:j===0?28+labelW:28,y:760-j*8,size:6.5,font}));descBottom=755-lines.length*8}p.drawPage(e,{x:(595.28-dw)/2,y:45+Math.max(0,(descBottom-45-dh)/2),width:dw,height:dh})}}catch(e){console.warn(e)}}return out}
async function stamp(p:PDFDocument){const f=await p.embedFont(StandardFonts.Helvetica),c=rgb(CYAN[0]/255,CYAN[1]/255,CYAN[2]/255),ps=p.getPages();ps.forEach((x,i)=>{const{width}=x.getSize();x.drawLine({start:{x:28,y:39},end:{x:width-28,y:39},thickness:.45,color:c});['Companhia de Saneamento Básico do Estado de São Paulo - Sabesp','Divisão de Manutenção e Serviços Operacionais Suzano - OLMS','Rua Benjamin Constant 1980 - Centro | CEP 08674-179 | Suzano - SP','www.sabesp.com.br'].forEach((t,j)=>x.drawText(t,{x:28,y:30-j*6,size:5.2,font:f,color:c}));x.drawText(`${i+1} de ${ps.length}`,{x:width-58,y:13,size:6.2,font:f,color:c})})}
export async function generatePhotoPdf(r:PhotoReport){const b=await base(r),p=await merge(b,r);await stamp(p);const bytes=await p.save({useObjectStreams:true}),blob=new Blob([bytes as unknown as BlobPart],{type:'application/pdf'});return{blob,url:URL.createObjectURL(blob),fileName:`${photoFileNameBase(r)}.pdf`}}
